target 'StickerPipe' do

platform :ios, '8.0'

use_frameworks!
pod 'MD5Digest', '~> 1.1'
pod 'RMStore', '~> 0.7'
pod 'RMStore/KeychainPersistence'
pod 'RMStore/NSUserDefaultsPersistence'
pod 'SSKeychain', '~> 1.3'
#pod 'StickerPipe', :path => '/Users/kirillklebanov/Documents/Code/Small app/StkiOS'

end
